Install the python package pymerkle, if you haven't yet (requires python ver 3.10+)

In [1]:
pip install pymerkle

Requirement already satisfied: pymerkle in c:\users\prágai bálint\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (6.1.0)
Requirement already satisfied: cachetools==5.3.1 in c:\users\prágai bálint\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pymerkle) (5.3.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\Prágai Bálint\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Reading the sinthetic user data

In [ ]:
import pandas as pd

df = pd.read_csv('./generated_table_data/users.csv')

df.iloc[0]

id                                       1
user_full_name                      User 1
city                                London
gender                                male
age                                     66
email                    user1@example.com
phone                          35840958516
bookingtime            2025-01-01 09:00:00
complaint                Burning sensation
satisfaction_rating                      4
allergy                             Pollen
Name: 0, dtype: object

In [3]:
"""
Helper functions for pseudo-anonymization of the data.
"""

def age_bucketer(age):
    match age:
        case age if age < 18:
            return 'under 18'
        case age if age < 25:
            return '18-25'
        case age if age < 40:
            return '25-39'
        case age if age < 66:
            return '40-65'
        case age if age < 80:
            return '66-79'
        case _:
            return '80+'
        
def geopolygon_bucketer(geopolygon):
    match geopolygon:
        case geopolygon if geopolygon == "Helsinki":
            return 'FI-Uusimaa'
        case geopolygon if geopolygon == "Tampere":
                return 'FI-Pirkanmaa'
        case geopolygon if geopolygon == "Stockholm":
            return 'SE-Stockholm'
        case geopolygon if geopolygon == "Berlin":
            return 'DE-Berlin'
        case geopolygon if geopolygon == "London":
            return 'UK-London'
        case geopolygon if geopolygon == "Austin":
            return 'US-Austin'
        case geopolygon if geopolygon == "Tokyo":
            return 'JP-Tokyo'
        case geopolygon if geopolygon == "Singapore":
            return 'SG-Singapore'
        case _:
            return 'other'

### Fixmetree ###
Below is the FixmeTree, a class based on the BaseMerkleTree, customized for this application.

In [4]:
from pymerkle import BaseMerkleTree

class FixmeTree(BaseMerkleTree):

    def __init__(self, algorithm='sha256'):
        """
        Storage setup and superclass initialization
        """
        self.hashes = []

        super().__init__(algorithm)

    @staticmethod
    def preprocess_entry(data):
        """
        Preprocesses data entry before encoding
        e.g. {age: 25, city: "Helsinki"} -> b'{"age_range": 18-25, "geopolygon": "FI-Uusimaa"}'
        """
        if isinstance(data, pd.Series):
            data = data.copy()
            data['age_range'] = age_bucketer(data['age'])
            data['geopolygon'] = geopolygon_bucketer(data['city'])
            data = data.drop(labels=['user_full_name', 'email', 'phone', 'age', 'city'])
            
        return data
    
    def _encode_entry(self, data):
        """
        Prepares data entry for hashing
        """
        proc_data = str(data)
        encoded_data = proc_data.encode('utf-8')
        return encoded_data
        
    def _store_leaf(self, data, digest):
        """
        Stores data hash in a new leaf and returns index
        """
        self.hashes += [digest]

        return len(self.hashes)


    def _get_leaf(self, index):
        """
        Returns the hash stored by the leaf specified
        """
        value = self.hashes[index - 1]

        return value


    def _get_leaves(self, offset, width):
        """
        Returns hashes corresponding to the specified leaf range
        """
        values = self.hashes[offset: offset + width]

        return values


    def _get_size(self):
        """
        Returns the current number of leaves
        """
        return len(self.hashes)

### Small scale demonstration ###
tree_medium is encoding a single row (= a single user) into a Merkle tree.
Per user encoding allows for per-row criteria matching.

In [5]:
tree_medium = FixmeTree(algorithm='sha256')
data = FixmeTree.preprocess_entry(df.iloc[0])
print(data)
for i in range(len(data)):
    tree_medium.append_entry(data.iloc[i])

print(f'tree size: {tree_medium.get_size()}')
print(f'tree state: {tree_medium.get_state().hex()}')

id                                       1
gender                                male
bookingtime            2025-01-01 09:00:00
complaint                Burning sensation
satisfaction_rating                      4
allergy                             Pollen
age_range                            66-79
geopolygon                       UK-London
Name: 0, dtype: object
tree size: 8
tree state: 5908decf242bb29d443cb6ccfec1c6a65ae867af160915f274c0f43b7bc7bd2f

### Small scale proof generation and verification ###
Due to some limitations of the current version of the package, the best way to prove data is within the entry is to create a single leaf tree.
As can be seen in the first example below, verify inclusion does not give and error, meaning the first entry's hash is indeed equal to the hash of the single leaf tree, both encoding the id '1'.
The second example shows, that id '2' is not included.

In [6]:
from pymerkle import verify_inclusion

prove_tree_true = FixmeTree(algorithm='sha256')
prove_tree_true.append_entry('male')

proof = tree_medium.prove_inclusion(2,8)
base = prove_tree_true.get_leaf(1)
root = tree_medium.get_state(8)

verify_inclusion(base, root, proof)

In [8]:
prove_tree_forged = FixmeTree(algorithm='sha256')
prove_tree_forged.append_entry('female')

proof = tree_medium.prove_inclusion(2,8)
base = prove_tree_forged.get_leaf(1)
root = tree_medium.get_state(8)

verify_inclusion(base, root, proof)

InvalidProof: Base hash does not match

### Medium scale example ###
In this example we can see how the algorith performs on 1000 users. All of them are being attribute-wise encoded and the appended to the Merkle-tree.

In [9]:
tree_large = FixmeTree(algorithm='sha256')

for i in range(1000):
    data = FixmeTree.preprocess_entry(df.iloc[i])
    for j in range(len(data)):
        print(f'entry {i} leaf {j}')
        tree_large.append_entry(data[j])

print(f'tree size: {tree_large.get_size()}')
print(f'tree state: {tree_large.get_state().hex()}')

entry 0 leaf 0
entry 0 leaf 1
entry 0 leaf 2
entry 0 leaf 3
entry 0 leaf 4
entry 0 leaf 5
entry 0 leaf 6
entry 0 leaf 7
entry 1 leaf 0
entry 1 leaf 1
entry 1 leaf 2
entry 1 leaf 3
entry 1 leaf 4
entry 1 leaf 5
entry 1 leaf 6
entry 1 leaf 7
entry 2 leaf 0
entry 2 leaf 1
entry 2 leaf 2
entry 2 leaf 3
entry 2 leaf 4
entry 2 leaf 5
entry 2 leaf 6
entry 2 leaf 7
entry 3 leaf 0
entry 3 leaf 1
entry 3 leaf 2
entry 3 leaf 3
entry 3 leaf 4
entry 3 leaf 5
entry 3 leaf 6
entry 3 leaf 7
entry 4 leaf 0
entry 4 leaf 1
entry 4 leaf 2
entry 4 leaf 3
entry 4 leaf 4
entry 4 leaf 5
entry 4 leaf 6
entry 4 leaf 7
entry 5 leaf 0
entry 5 leaf 1
entry 5 leaf 2
entry 5 leaf 3
entry 5 leaf 4
entry 5 leaf 5
entry 5 leaf 6
entry 5 leaf 7
entry 6 leaf 0
entry 6 leaf 1
entry 6 leaf 2
entry 6 leaf 3
entry 6 leaf 4
entry 6 leaf 5
entry 6 leaf 6
entry 6 leaf 7
entry 7 leaf 0
entry 7 leaf 1
entry 7 leaf 2
entry 7 leaf 3
entry 7 leaf 4
entry 7 leaf 5
entry 7 leaf 6
entry 7 leaf 7
entry 8 leaf 0
entry 8 leaf 1
entry 8 leaf 2
entry 8 leaf 3
entry 8 leaf 4
entry 8 leaf 5
entry 8 leaf 6
entry 8 leaf 7
entry 9 leaf 0
entry 9 leaf 1
entry 9 leaf 2
entry 9 leaf 3
entry 9 leaf 4
entry 9 leaf 5
entry 9 leaf 6
entry 9 leaf 7
entry 10 leaf 0
entry 10 leaf 1
entry 10 leaf 2
entry 10 leaf 3
entry 10 leaf 4
entry 10 leaf 5
entry 10 leaf 6
entry 10 leaf 7
entry 11 leaf 0
entry 11 leaf 1
entry 11 leaf 2
entry 11 leaf 3
entry 11 leaf 4
entry 11 leaf 5
entry 11 leaf 6
entry 11 leaf 7
entry 12 leaf 0
entry 12 leaf 1
entry 12 leaf 2
entry 12 leaf 3
entry 12 leaf 4
entry 12 leaf 5
entry 12 leaf 6
entry 12 leaf 7
entry 13 leaf 0
entry 13 leaf 1
entry 13 leaf 2
entry 13 leaf 3
entry 13 leaf 4
entry 13 leaf 5
entry 13 leaf 6
entry 13 leaf 7
entry 14 leaf 0
entry 14 leaf 1
entry 14 leaf 2
entry 14 leaf 3
entry 14 leaf 4
entry 14 leaf 5
entry 14 leaf 6
entry 14 leaf 7
entry 15 leaf 0
entry 15 leaf 1
entry 15 leaf 2
entry 15 leaf 3
entry 15 leaf 4
entry 15 leaf 5
entry 15 leaf 6
entry 15 leaf 7
entry 16 leaf 0
entry 16 leaf 1
entry 16 leaf 2
entry 16 leaf 3
entry 16 leaf 4
entry 16 leaf 5
entry 16 leaf 6
entry 16 leaf 7
entry 17 leaf 0
entry 17 leaf 1
entry 17 leaf 2
entry 17 leaf 3
entry 17 leaf 4
entry 17 leaf 5
entry 17 leaf 6
entry 17 leaf 7
entry 18 leaf 0
entry 18 leaf 1
entry 18 leaf 2
entry 18 leaf 3
entry 18 leaf 4
entry 18 leaf 5
entry 18 leaf 6
entry 18 leaf 7
entry 19 leaf 0
entry 19 leaf 1
entry 19 leaf 2
entry 19 leaf 3
entry 19 leaf 4
entry 19 leaf 5
entry 19 leaf 6
entry 19 leaf 7
entry 20 leaf 0
entry 20 leaf 1
entry 20 leaf 2
entry 20 leaf 3
entry 20 leaf 4
entry 20 leaf 5
entry 20 leaf 6
entry 20 leaf 7
entry 21 leaf 0
entry 21 leaf 1
entry 21 leaf 2
entry 21 leaf 3
entry 21 leaf 4
entry 21 leaf 5
entry 21 leaf 6
entry 21 leaf 7
entry 22 leaf 0
entry 22 leaf 1
entry 22 leaf 2
entry 22 leaf 3
entry 22 leaf 4
entry 22 leaf 5
entry 22 leaf 6
entry 22 leaf 7
entry 23 leaf 0
entry 23 leaf 1
entry 23 leaf 2
entry 23 leaf 3
entry 23 leaf 4
entry 23 leaf 5
entry 23 leaf 6
entry 23 leaf 7
entry 24 leaf 0
entry 24 leaf 1
entry 24 leaf 2
entry 24 leaf 3
entry 24 leaf 4
entry 24 leaf 5
entry 24 leaf 6
entry 24 leaf 7
entry 25 leaf 0
entry 25 leaf 1
entry 25 leaf 2
entry 25 leaf 3
entry 25 leaf 4
entry 25 leaf 5
entry 25 leaf 6
entry 25 leaf 7
entry 26 leaf 0
entry 26 leaf 1
entry 26 leaf 2
entry 26 leaf 3
entry 26 leaf 4
entry 26 leaf 5
entry 26 leaf 6
entry 26 leaf 7
entry 27 leaf 0
entry 27 leaf 1
entry 27 leaf 2
entry 27 leaf 3
entry 27 leaf 4
entry 27 leaf 5
entry 27 leaf 6
entry 27 leaf 7
entry 28 leaf 0
entry 28 leaf 1
entry 28 leaf 2
entry 28 leaf 3
entry 28 leaf 4
entry 28 leaf 5
entry 28 leaf 6
entry 28 leaf 7
entry 29 leaf 0
entry 29 leaf 1
entry 29 leaf 2
entry 29 leaf 3
entry 29 leaf 4
entry 29 leaf 5
entry 29 leaf 6
entry 29 leaf 7
entry 30 leaf 0
entry 30 leaf 1
entry 30 leaf 2
entry 30 leaf 3
entry 30 leaf 4
entry 30 leaf 5
entry 30 leaf 6
entry 30 leaf 7
entry 31 leaf 0
entry 31 leaf 1
entry 31 leaf 2
entry 31 leaf 3
entry 31 leaf 4
entry 31 leaf 5
entry 31 leaf 6
entry 31 leaf 7
entry 32 leaf 0
entry 32 leaf 1
entry 32 leaf 2
entry 32 leaf 3
entry 32 leaf 4
entry 32 leaf 5
entry 32 leaf 6
entry 32 leaf 7
entry 33 leaf 0
entry 33 leaf 1
entry 33 leaf 2
entry 33 leaf 3
entry 33 leaf 4
entry 33 leaf 5
entry 33 leaf 6
entry 33 leaf 7
entry 34 leaf 0
entry 34 leaf 1
entry 34 leaf 2
entry 34 leaf 3
entry 34 leaf 4
entry 34 leaf 5
entry 34 leaf 6
entry 34 leaf 7
entry 35 leaf 0
entry 35 leaf 1
entry 35 leaf 2
entry 35 leaf 3
entry 35 leaf 4
entry 35 leaf 5
entry 35 leaf 6
entry 35 leaf 7
entry 36 leaf 0
entry 36 leaf 1
entry 36 leaf 2
entry 36 leaf 3
entry 36 leaf 4
entry 36 leaf 5
entry 36 leaf 6
entry 36 leaf 7
entry 37 leaf 0
entry 37 leaf 1
entry 37 leaf 2
entry 37 leaf 3
entry 37 leaf 4
entry 37 leaf 5
entry 37 leaf 6
entry 37 leaf 7
entry 38 leaf 0
entry 38 leaf 1
entry 38 leaf 2
entry 38 leaf 3
entry 38 leaf 4
entry 38 leaf 5
entry 38 leaf 6
entry 38 leaf 7
entry 39 leaf 0
entry 39 leaf 1
entry 39 leaf 2
entry 39 leaf 3
entry 39 leaf 4
entry 39 leaf 5
entry 39 leaf 6
entry 39 leaf 7
entry 40 leaf 0
entry 40 leaf 1
entry 40 leaf 2
entry 40 leaf 3
entry 40 leaf 4
entry 40 leaf 5
entry 40 leaf 6
entry 40 leaf 7
entry 41 leaf 0
entry 41 leaf 1
entry 41 leaf 2
entry 41 leaf 3
entry 41 leaf 4
entry 41 leaf 5
entry 41 leaf 6
entry 41 leaf 7
entry 42 leaf 0
entry 42 leaf 1
entry 42 leaf 2
entry 42 leaf 3
entry 42 leaf 4
entry 42 leaf 5
entry 42 leaf 6
entry 42 leaf 7
entry 43 leaf 0
entry 43 leaf 1
entry 43 leaf 2
entry 43 leaf 3
entry 43 leaf 4
entry 43 leaf 5
entry 43 leaf 6
entry 43 leaf 7
entry 44 leaf 0
entry 44 leaf 1
entry 44 leaf 2
entry 44 leaf 3
entry 44 leaf 4
entry 44 leaf 5
entry 44 leaf 6
entry 44 leaf 7
entry 45 leaf 0
entry 45 leaf 1
entry 45 leaf 2
entry 45 leaf 3
entry 45 leaf 4
entry 45 leaf 5
entry 45 leaf 6
entry 45 leaf 7
entry 46 leaf 0
entry 46 leaf 1
entry 46 leaf 2
entry 46 leaf 3
entry 46 leaf 4
entry 46 leaf 5
entry 46 leaf 6
entry 46 leaf 7
entry 47 leaf 0
entry 47 leaf 1
entry 47 leaf 2
entry 47 leaf 3
entry 47 leaf 4
entry 47 leaf 5
entry 47 leaf 6
entry 47 leaf 7
entry 48 leaf 0
entry 48 leaf 1
entry 48 leaf 2
entry 48 leaf 3
entry 48 leaf 4
entry 48 leaf 5
entry 48 leaf 6
entry 48 leaf 7
entry 49 leaf 0
entry 49 leaf 1
entry 49 leaf 2
entry 49 leaf 3
entry 49 leaf 4
entry 49 leaf 5
entry 49 leaf 6
entry 49 leaf 7
entry 50 leaf 0
entry 50 leaf 1
entry 50 leaf 2
entry 50 leaf 3
entry 50 leaf 4
entry 50 leaf 5
entry 50 leaf 6
entry 50 leaf 7
entry 51 leaf 0
entry 51 leaf 1
entry 51 leaf 2
entry 51 leaf 3
entry 51 leaf 4
entry 51 leaf 5
entry 51 leaf 6
entry 51 leaf 7
entry 52 leaf 0
entry 52 leaf 1
entry 52 leaf 2
entry 52 leaf 3
entry 52 leaf 4
entry 52 leaf 5
entry 52 leaf 6
entry 52 leaf 7
entry 53 leaf 0
entry 53 leaf 1
entry 53 leaf 2
entry 53 leaf 3
entry 53 leaf 4
entry 53 leaf 5
entry 53 leaf 6
entry 53 leaf 7
entry 54 leaf 0
entry 54 leaf 1
entry 54 leaf 2
entry 54 leaf 3
entry 54 leaf 4
entry 54 leaf 5
entry 54 leaf 6
entry 54 leaf 7
entry 55 leaf 0
entry 55 leaf 1
entry 55 leaf 2
entry 55 leaf 3
entry 55 leaf 4
entry 55 leaf 5
entry 55 leaf 6
entry 55 leaf 7
entry 56 leaf 0
entry 56 leaf 1
entry 56 leaf 2
entry 56 leaf 3
entry 56 leaf 4
entry 56 leaf 5
entry 56 leaf 6
entry 56 leaf 7
entry 57 leaf 0
entry 57 leaf 1
entry 57 leaf 2
entry 57 leaf 3
entry 57 leaf 4
entry 57 leaf 5
entry 57 leaf 6
entry 57 leaf 7
entry 58 leaf 0
entry 58 leaf 1
entry 58 leaf 2
entry 58 leaf 3
entry 58 leaf 4
entry 58 leaf 5
entry 58 leaf 6
entry 58 leaf 7
entry 59 leaf 0
entry 59 leaf 1
entry 59 leaf 2
entry 59 leaf 3
entry 59 leaf 4
entry 59 leaf 5
entry 59 leaf 6
entry 59 leaf 7
entry 60 leaf 0
entry 60 leaf 1
entry 60 leaf 2
entry 60 leaf 3
entry 60 leaf 4
entry 60 leaf 5
entry 60 leaf 6
entry 60 leaf 7
entry 61 leaf 0
entry 61 leaf 1
entry 61 leaf 2
entry 61 leaf 3
entry 61 leaf 4
entry 61 leaf 5
entry 61 leaf 6
entry 61 leaf 7
entry 62 leaf 0
entry 62 leaf 1
entry 62 leaf 2
entry 62 leaf 3
entry 62 leaf 4
entry 62 leaf 5
entry 62 leaf 6
entry 62 leaf 7
entry 63 leaf 0
entry 63 leaf 1
entry 63 leaf 2
entry 63 leaf 3
entry 63 leaf 4
entry 63 leaf 5
entry 63 leaf 6
entry 63 leaf 7
entry 64 leaf 0
entry 64 leaf 1
entry 64 leaf 2
entry 64 leaf 3
entry 64 leaf 4
entry 64 leaf 5
entry 64 leaf 6
entry 64 leaf 7
entry 65 leaf 0
entry 65 leaf 1
entry 65 leaf 2
entry 65 leaf 3
entry 65 leaf 4
entry 65 leaf 5
entry 65 leaf 6
entry 65 leaf 7
entry 66 leaf 0
entry 66 leaf 1
entry 66 leaf 2
entry 66 leaf 3
entry 66 leaf 4
entry 66 leaf 5
entry 66 leaf 6
entry 66 leaf 7
entry 67 leaf 0
entry 67 leaf 1
entry 67 leaf 2
entry 67 leaf 3
entry 67 leaf 4
entry 67 leaf 5
entry 67 leaf 6
entry 67 leaf 7
entry 68 leaf 0
entry 68 leaf 1
entry 68 leaf 2
entry 68 leaf 3
entry 68 leaf 4
entry 68 leaf 5
entry 68 leaf 6
entry 68 leaf 7
entry 69 leaf 0
entry 69 leaf 1
entry 69 leaf 2
entry 69 leaf 3
entry 69 leaf 4
entry 69 leaf 5
entry 69 leaf 6
entry 69 leaf 7
entry 70 leaf 0
entry 70 leaf 1
entry 70 leaf 2
entry 70 leaf 3
entry 70 leaf 4
entry 70 leaf 5
entry 70 leaf 6
entry 70 leaf 7
entry 71 leaf 0
entry 71 leaf 1
entry 71 leaf 2
entry 71 leaf 3
entry 71 leaf 4
entry 71 leaf 5
entry 71 leaf 6
entry 71 leaf 7
entry 72 leaf 0
entry 72 leaf 1
entry 72 leaf 2
entry 72 leaf 3
entry 72 leaf 4
entry 72 leaf 5
entry 72 leaf 6
entry 72 leaf 7
entry 73 leaf 0
entry 73 leaf 1
entry 73 leaf 2
entry 73 leaf 3
entry 73 leaf 4
entry 73 leaf 5
entry 73 leaf 6
entry 73 leaf 7
entry 74 leaf 0
entry 74 leaf 1
entry 74 leaf 2
entry 74 leaf 3
entry 74 leaf 4
entry 74 leaf 5
entry 74 leaf 6
entry 74 leaf 7
entry 75 leaf 0
entry 75 leaf 1
entry 75 leaf 2
entry 75 leaf 3
entry 75 leaf 4
entry 75 leaf 5
entry 75 leaf 6
entry 75 leaf 7
entry 76 leaf 0
entry 76 leaf 1
entry 76 leaf 2
entry 76 leaf 3
entry 76 leaf 4
entry 76 leaf 5
entry 76 leaf 6
entry 76 leaf 7
entry 77 leaf 0
entry 77 leaf 1
entry 77 leaf 2
entry 77 leaf 3
entry 77 leaf 4
entry 77 leaf 5
entry 77 leaf 6
entry 77 leaf 7
entry 78 leaf 0
entry 78 leaf 1
entry 78 leaf 2
entry 78 leaf 3
entry 78 leaf 4
entry 78 leaf 5
entry 78 leaf 6
entry 78 leaf 7
entry 79 leaf 0
entry 79 leaf 1
entry 79 leaf 2
entry 79 leaf 3
entry 79 leaf 4
entry 79 leaf 5
entry 79 leaf 6
entry 79 leaf 7
entry 80 leaf 0
entry 80 leaf 1
entry 80 leaf 2
entry 80 leaf 3
entry 80 leaf 4
entry 80 leaf 5
entry 80 leaf 6
entry 80 leaf 7
entry 81 leaf 0
entry 81 leaf 1
entry 81 leaf 2
entry 81 leaf 3
entry 81 leaf 4
entry 81 leaf 5
entry 81 leaf 6
entry 81 leaf 7
entry 82 leaf 0
entry 82 leaf 1
entry 82 leaf 2
entry 82 leaf 3
entry 82 leaf 4
entry 82 leaf 5
entry 82 leaf 6
entry 82 leaf 7
entry 83 leaf 0
entry 83 leaf 1
entry 83 leaf 2
entry 83 leaf 3
entry 83 leaf 4
entry 83 leaf 5
entry 83 leaf 6
entry 83 leaf 7
entry 84 leaf 0
entry 84 leaf 1
entry 84 leaf 2
entry 84 leaf 3
entry 84 leaf 4
entry 84 leaf 5
entry 84 leaf 6
entry 84 leaf 7
entry 85 leaf 0
entry 85 leaf 1
entry 85 leaf 2
entry 85 leaf 3
entry 85 leaf 4
entry 85 leaf 5
entry 85 leaf 6
entry 85 leaf 7
entry 86 leaf 0
entry 86 leaf 1
entry 86 leaf 2
entry 86 leaf 3
entry 86 leaf 4
entry 86 leaf 5
entry 86 leaf 6
entry 86 leaf 7
entry 87 leaf 0
entry 87 leaf 1
entry 87 leaf 2
entry 87 leaf 3
entry 87 leaf 4
entry 87 leaf 5
entry 87 leaf 6
entry 87 leaf 7
entry 88 leaf 0
entry 88 leaf 1
entry 88 leaf 2
entry 88 leaf 3
entry 88 leaf 4
entry 88 leaf 5
entry 88 leaf 6
entry 88 leaf 7
entry 89 leaf 0
entry 89 leaf 1
entry 89 leaf 2
entry 89 leaf 3
entry 89 leaf 4
entry 89 leaf 5
entry 89 leaf 6
entry 89 leaf 7
entry 90 leaf 0
entry 90 leaf 1
entry 90 leaf 2
entry 90 leaf 3
entry 90 leaf 4
entry 90 leaf 5
entry 90 leaf 6
entry 90 leaf 7
entry 91 leaf 0
entry 91 leaf 1
entry 91 leaf 2
entry 91 leaf 3
entry 91 leaf 4
entry 91 leaf 5
entry 91 leaf 6
entry 91 leaf 7
entry 92 leaf 0
entry 92 leaf 1
entry 92 leaf 2
entry 92 leaf 3
entry 92 leaf 4
entry 92 leaf 5
entry 92 leaf 6
entry 92 leaf 7
entry 93 leaf 0
entry 93 leaf 1
entry 93 leaf 2
entry 93 leaf 3
entry 93 leaf 4
entry 93 leaf 5
entry 93 leaf 6
entry 93 leaf 7
entry 94 leaf 0
entry 94 leaf 1
entry 94 leaf 2
entry 94 leaf 3
entry 94 leaf 4
entry 94 leaf 5
entry 94 leaf 6
entry 94 leaf 7
entry 95 leaf 0
entry 95 leaf 1
entry 95 leaf 2
entry 95 leaf 3
entry 95 leaf 4
entry 95 leaf 5
entry 95 leaf 6
entry 95 leaf 7
entry 96 leaf 0
entry 96 leaf 1
entry 96 leaf 2
entry 96 leaf 3
entry 96 leaf 4
entry 96 leaf 5
entry 96 leaf 6
entry 96 leaf 7
entry 97 leaf 0
entry 97 leaf 1
entry 97 leaf 2
entry 97 leaf 3
entry 97 leaf 4
entry 97 leaf 5
entry 97 leaf 6
entry 97 leaf 7
entry 98 leaf 0
entry 98 leaf 1
entry 98 leaf 2
entry 98 leaf 3
entry 98 leaf 4
entry 98 leaf 5
entry 98 leaf 6
entry 98 leaf 7
entry 99 leaf 0
entry 99 leaf 1
entry 99 leaf 2
entry 99 leaf 3
entry 99 leaf 4
entry 99 leaf 5
entry 99 leaf 6
entry 99 leaf 7
entry 100 leaf 0
entry 100 leaf 1
entry 100 leaf 2
entry 100 leaf 3
entry 100 leaf 4
entry 100 leaf 5
entry 100 leaf 6
entry 100 leaf 7
entry 101 leaf 0
entry 101 leaf 1
entry 101 leaf 2
entry 101 leaf 3
entry 101 leaf 4
entry 101 leaf 5
entry 101 leaf 6
entry 101 leaf 7
entry 102 leaf 0
entry 102 leaf 1
entry 102 leaf 2
entry 102 leaf 3
entry 102 leaf 4
entry 102 leaf 5
entry 102 leaf 6
entry 102 leaf 7
entry 103 leaf 0
entry 103 leaf 1
entry 103 leaf 2
entry 103 leaf 3
entry 103 leaf 4
entry 103 leaf 5
entry 103 leaf 6
entry 103 leaf 7
entry 104 leaf 0
entry 104 leaf 1
entry 104 leaf 2
entry 104 leaf 3
entry 104 leaf 4
entry 104 leaf 5
entry 104 leaf 6
entry 104 leaf 7
entry 105 leaf 0
entry 105 leaf 1
entry 105 leaf 2
entry 105 leaf 3
entry 105 leaf 4
entry 105 leaf 5
entry 105 leaf 6
entry 105 leaf 7
entry 106 leaf 0
entry 106 leaf 1
entry 106 leaf 2
entry 106 leaf 3
entry 106 leaf 4
entry 106 leaf 5
entry 106 leaf 6
entry 106 leaf 7
entry 107 leaf 0
entry 107 leaf 1
entry 107 leaf 2
entry 107 leaf 3
entry 107 leaf 4
entry 107 leaf 5
entry 107 leaf 6
entry 107 leaf 7
entry 108 leaf 0
entry 108 leaf 1
entry 108 leaf 2
entry 108 leaf 3
entry 108 leaf 4
entry 108 leaf 5
entry 108 leaf 6
entry 108 leaf 7
entry 109 leaf 0
entry 109 leaf 1
entry 109 leaf 2
entry 109 leaf 3
entry 109 leaf 4
entry 109 leaf 5
entry 109 leaf 6
entry 109 leaf 7
entry 110 leaf 0
entry 110 leaf 1
entry 110 leaf 2
entry 110 leaf 3
entry 110 leaf 4
entry 110 leaf 5
entry 110 leaf 6
entry 110 leaf 7
entry 111 leaf 0
entry 111 leaf 1
entry 111 leaf 2
entry 111 leaf 3
entry 111 leaf 4
entry 111 leaf 5
entry 111 leaf 6
entry 111 leaf 7
entry 112 leaf 0
entry 112 leaf 1
entry 112 leaf 2
entry 112 leaf 3
entry 112 leaf 4
entry 112 leaf 5
entry 112 leaf 6
entry 112 leaf 7
entry 113 leaf 0
entry 113 leaf 1
entry 113 leaf 2
entry 113 leaf 3
entry 113 leaf 4
entry 113 leaf 5
entry 113 leaf 6
entry 113 leaf 7
entry 114 leaf 0
entry 114 leaf 1
entry 114 leaf 2
entry 114 leaf 3
entry 114 leaf 4
entry 114 leaf 5
entry 114 leaf 6
entry 114 leaf 7
entry 115 leaf 0
entry 115 leaf 1
entry 115 leaf 2
entry 115 leaf 3
entry 115 leaf 4
entry 115 leaf 5
entry 115 leaf 6
entry 115 leaf 7
entry 116 leaf 0
entry 116 leaf 1
entry 116 leaf 2
entry 116 leaf 3
entry 116 leaf 4
entry 116 leaf 5
entry 116 leaf 6
entry 116 leaf 7
entry 117 leaf 0
entry 117 leaf 1
entry 117 leaf 2
entry 117 leaf 3
entry 117 leaf 4
entry 117 leaf 5
entry 117 leaf 6
entry 117 leaf 7
entry 118 leaf 0
entry 118 leaf 1
entry 118 leaf 2
entry 118 leaf 3
entry 118 leaf 4
entry 118 leaf 5
entry 118 leaf 6
entry 118 leaf 7
entry 119 leaf 0
entry 119 leaf 1
entry 119 leaf 2
entry 119 leaf 3
entry 119 leaf 4
entry 119 leaf 5
entry 119 leaf 6
entry 119 leaf 7
entry 120 leaf 0
entry 120 leaf 1
entry 120 leaf 2
entry 120 leaf 3
entry 120 leaf 4
entry 120 leaf 5
entry 120 leaf 6
entry 120 leaf 7
entry 121 leaf 0
entry 121 leaf 1
entry 121 leaf 2
entry 121 leaf 3
entry 121 leaf 4
entry 121 leaf 5
entry 121 leaf 6
entry 121 leaf 7
entry 122 leaf 0
entry 122 leaf 1
entry 122 leaf 2
entry 122 leaf 3
entry 122 leaf 4
entry 122 leaf 5
entry 122 leaf 6
entry 122 leaf 7
entry 123 leaf 0
entry 123 leaf 1
entry 123 leaf 2
entry 123 leaf 3
entry 123 leaf 4
entry 123 leaf 5
entry 123 leaf 6
entry 123 leaf 7
entry 124 leaf 0
entry 124 leaf 1
entry 124 leaf 2
entry 124 leaf 3
entry 124 leaf 4
entry 124 leaf 5
entry 124 leaf 6
entry 124 leaf 7
entry 125 leaf 0
entry 125 leaf 1
entry 125 leaf 2
entry 125 leaf 3
entry 125 leaf 4
entry 125 leaf 5
entry 125 leaf 6
entry 125 leaf 7
entry 126 leaf 0
entry 126 leaf 1
entry 126 leaf 2
entry 126 leaf 3
entry 126 leaf 4
entry 126 leaf 5
entry 126 leaf 6
entry 126 leaf 7
entry 127 leaf 0
entry 127 leaf 1
entry 127 leaf 2
entry 127 leaf 3
entry 127 leaf 4
entry 127 leaf 5
entry 127 leaf 6
entry 127 leaf 7
entry 128 leaf 0
entry 128 leaf 1
entry 128 leaf 2
entry 128 leaf 3
entry 128 leaf 4
entry 128 leaf 5
entry 128 leaf 6
entry 128 leaf 7
entry 129 leaf 0
entry 129 leaf 1
entry 129 leaf 2
entry 129 leaf 3
entry 129 leaf 4
entry 129 leaf 5
entry 129 leaf 6
entry 129 leaf 7
entry 130 leaf 0
entry 130 leaf 1
entry 130 leaf 2
entry 130 leaf 3
entry 130 leaf 4
entry 130 leaf 5
entry 130 leaf 6
entry 130 leaf 7
entry 131 leaf 0
entry 131 leaf 1
entry 131 leaf 2
entry 131 leaf 3
entry 131 leaf 4
entry 131 leaf 5
entry 131 leaf 6
entry 131 leaf 7
entry 132 leaf 0
entry 132 leaf 1
entry 132 leaf 2
entry 132 leaf 3
entry 132 leaf 4
entry 132 leaf 5
entry 132 leaf 6
entry 132 leaf 7
entry 133 leaf 0
entry 133 leaf 1
entry 133 leaf 2
entry 133 leaf 3
entry 133 leaf 4
entry 133 leaf 5
entry 133 leaf 6
entry 133 leaf 7
entry 134 leaf 0
entry 134 leaf 1
entry 134 leaf 2
entry 134 leaf 3
entry 134 leaf 4
entry 134 leaf 5
entry 134 leaf 6
entry 134 leaf 7
entry 135 leaf 0
entry 135 leaf 1
entry 135 leaf 2
entry 135 leaf 3
entry 135 leaf 4
entry 135 leaf 5
entry 135 leaf 6
entry 135 leaf 7
entry 136 leaf 0
entry 136 leaf 1
entry 136 leaf 2
entry 136 leaf 3
entry 136 leaf 4
entry 136 leaf 5
entry 136 leaf 6
entry 136 leaf 7
entry 137 leaf 0
entry 137 leaf 1
entry 137 leaf 2
entry 137 leaf 3
entry 137 leaf 4
entry 137 leaf 5
entry 137 leaf 6
entry 137 leaf 7
entry 138 leaf 0
entry 138 leaf 1
entry 138 leaf 2
entry 138 leaf 3
entry 138 leaf 4
entry 138 leaf 5
entry 138 leaf 6
entry 138 leaf 7
entry 139 leaf 0
entry 139 leaf 1
entry 139 leaf 2
entry 139 leaf 3
entry 139 leaf 4
entry 139 leaf 5
entry 139 leaf 6
entry 139 leaf 7
entry 140 leaf 0
entry 140 leaf 1
entry 140 leaf 2
entry 140 leaf 3
entry 140 leaf 4
entry 140 leaf 5
entry 140 leaf 6
entry 140 leaf 7
entry 141 leaf 0
entry 141 leaf 1
entry 141 leaf 2
entry 141 leaf 3
entry 141 leaf 4
entry 141 leaf 5
entry 141 leaf 6
entry 141 leaf 7
entry 142 leaf 0
entry 142 leaf 1
entry 142 leaf 2
entry 142 leaf 3
entry 142 leaf 4
entry 142 leaf 5
entry 142 leaf 6
entry 142 leaf 7
entry 143 leaf 0
entry 143 leaf 1
entry 143 leaf 2
entry 143 leaf 3
entry 143 leaf 4
entry 143 leaf 5
entry 143 leaf 6
entry 143 leaf 7
entry 144 leaf 0
entry 144 leaf 1
entry 144 leaf 2
entry 144 leaf 3
entry 144 leaf 4
entry 144 leaf 5
entry 144 leaf 6
entry 144 leaf 7
entry 145 leaf 0
entry 145 leaf 1
entry 145 leaf 2
entry 145 leaf 3
entry 145 leaf 4
entry 145 leaf 5
entry 145 leaf 6
entry 145 leaf 7
entry 146 leaf 0
entry 146 leaf 1
entry 146 leaf 2
entry 146 leaf 3
entry 146 leaf 4
entry 146 leaf 5
entry 146 leaf 6
entry 146 leaf 7
entry 147 leaf 0
entry 147 leaf 1
entry 147 leaf 2
entry 147 leaf 3
entry 147 leaf 4
entry 147 leaf 5
entry 147 leaf 6
entry 147 leaf 7
entry 148 leaf 0
entry 148 leaf 1
entry 148 leaf 2
entry 148 leaf 3
entry 148 leaf 4
entry 148 leaf 5
entry 148 leaf 6
entry 148 leaf 7
entry 149 leaf 0
entry 149 leaf 1
entry 149 leaf 2
entry 149 leaf 3
entry 149 leaf 4
entry 149 leaf 5
entry 149 leaf 6
entry 149 leaf 7
entry 150 leaf 0
entry 150 leaf 1
entry 150 leaf 2
entry 150 leaf 3
entry 150 leaf 4
entry 150 leaf 5
entry 150 leaf 6
entry 150 leaf 7
entry 151 leaf 0
entry 151 leaf 1
entry 151 leaf 2
entry 151 leaf 3
entry 151 leaf 4
entry 151 leaf 5
entry 151 leaf 6
entry 151 leaf 7
entry 152 leaf 0
entry 152 leaf 1
entry 152 leaf 2
entry 152 leaf 3
entry 152 leaf 4
entry 152 leaf 5
entry 152 leaf 6
entry 152 leaf 7
entry 153 leaf 0
entry 153 leaf 1
entry 153 leaf 2
entry 153 leaf 3

## Large scale encoding experiment ##
This time, we are creating a Merkle-tree for each user in the whole example database, meaning 10 000 Merkle trees; all with 8 leaves.

In [ ]:
encoded_df = []

for i in range(len(df)):
    entry = None
    locals()["user_tree_" + str(i)] = FixmeTree(algorithm='sha256')
    data = FixmeTree.preprocess_entry(df.iloc[i])
    for j in range(len(data)):
        #print(f'entry {i} leaf {j}')
        locals()["user_tree_" + str(i)].append_entry(data[j])
    encoded_df.append(locals()["user_tree_" + str(i)])

hex_data = pd.DataFrame(encoded_df)
hex_data

                                                      0
0     <__main__.FixmeTree object at 0x000002416BAE78E0>
1     <__main__.FixmeTree object at 0x000002416B7277F0>
2     <__main__.FixmeTree object at 0x000002416B5E40A0>
3     <__main__.FixmeTree object at 0x000002416BAE73D0>
4     <__main__.FixmeTree object at 0x000002416BAE6650>
...                                                 ...
9995  <__main__.FixmeTree object at 0x000002416DB8BC70>
9996  <__main__.FixmeTree object at 0x000002416DBD0640>
9997  <__main__.FixmeTree object at 0x000002416DBD02B0>
9998  <__main__.FixmeTree object at 0x000002416DBD02E0>
9999  <__main__.FixmeTree object at 0x000002416DBD0700>

[10000 rows x 1 columns]

### proof generation ###
Now we check if our encodings actually can prove inclusion:

In [ ]:
check = FixmeTree.preprocess_entry(df.iloc[0])
print(check)
check['age_range']

id                                       1
gender                                male
bookingtime            2025-01-01 09:00:00
complaint                Burning sensation
satisfaction_rating                      4
allergy                             Pollen
age_range                            66-79
geopolygon                       UK-London
Name: 0, dtype: object

'66-79'

In [ ]:
from pymerkle import verify_inclusion

user_tree = hex_data.iloc[0][0] #This is a FixMeTree object, not a hash
query_tree = FixmeTree(algorithm='sha256')
query_tree.append_entry(check['age_range'])

proof = user_tree.prove_inclusion(7, 8)
base = query_tree.get_leaf(1)
root = user_tree.get_state(8)

verify_inclusion(base, root, proof)

#### Hurray ####
And we get no errors, which means the proof is valid!
Now let's see an application for this on the whole dataset; How many of the participants are from the "UK-London" area?

In [ ]:
def test_geolocation_match(dataframe:pd.DataFrame, criteria: str, attribute: int):
    from pymerkle import verify_inclusion, InvalidProof
    
    matching_users = []

    query_tree = FixmeTree(algorithm='sha256')
    query_tree.append_entry(criteria)
    base = query_tree.get_leaf(1)

    for i in range(len(dataframe)):
        user_tree = dataframe.iloc[i][0]

        proof = user_tree.prove_inclusion(attribute, 8)
        root = user_tree.get_state(8)

        try:
            verify_inclusion(base, root, proof)
            matching_users.append(i)
        except InvalidProof:
            continue

    return matching_users

In [ ]:
london_users_lists = test_geolocation_match(hex_data, 'UK-London', 8)
london_users = df.iloc[london_users_lists]
london_users

,id,user_full_name,city,gender,age,email,phone,bookingtime,complaint,satisfaction_rating,allergy
0,1,User 1,London,male,66,user1@example.com,35840958516,2025-01-01 09:00:00,Burning sensation,4,Pollen
11,12,User 12,London,other,46,user12@example.com,35840332148,2025-01-02 18:00:00,Headache,4,Gluten
17,18,User 18,London,other,77,user18@example.com,35840913619,2025-01-03 12:00:00,Flu-like symptoms,1,Pollen
24,25,User 25,London,female,65,user25@example.com,35840155391,2025-01-04 09:00:00,Skin rash,3,Pollen
25,26,User 26,London,other,47,user26@example.com,35840589236,2025-01-04 12:00:00,Flu-like symptoms,4,Penicillin
...,...,...,...,...,...,...,...,...,...,...,...
9984,9985,User 9985,London,female,82,user9985@example.com,35840700983,2028-06-02 09:00:00,Headache,2,Pollen
9990,9991,User 9991,London,female,53,user9991@example.com,35840839144,2028-06-03 03:00:00,Flu-like symptoms,1,Penicillin
9993,9994,User 9994,London,female,30,user9994@example.com,35840802161,2028-06-03 12:00:00,Burning sensation,5,Gluten
9994,9995,User 9995,London,other,34,user9995@example.com,35840987217,2028-06-03 15:00:00,Flu-like symptoms,1,Pollen
9997,9998,User 9998,London,female,18,user9998@example.com,35840613008,2028-06-04 00:00:00,Burning sensation,4,Penicillin